### ISSUE TITLE
Multiple Accounts in Desktop Outlook Client

### ISSUE THREAD

**Issue by sheesetfs** [captainqwerty/AutomatedOutlookSignature#15]
### Problem:
The current Set-OutlookSignature.ps1 script generates a single signature file based on the Active Directory details of the user who is logged in. However, many users have multiple accounts configured in their desktop Outlook client.

### Issue Details:

**Scenario:** When a user has multiple email accounts in Outlook, the script only considers the Active Directory details of the account used during login.
**Impact:** This results in a uniform signature across all accounts, which may not accurately represent the information associated with each specific email account.
**User Experience:** Users with distinct roles or responsibilities across different accounts may find that the generated signature doesn't reflect the appropriate information for each account.

**Comment by captainqwerty** [comment]
@sheesetfs - apologies for the huge delay in looking into this.  I have had a lot on for the start of this year and have only just had time to come back to personal projects.

I have released a new re-write, version 5.0.0 but I have not yet taken this into consideration.

I am not 100% sure I understand the issue, would you mind explaining further? I understand if you are no longer active in this issue due to my huge delay.

Thank you.

**Comment by captainqwerty** [comment]
Thank you @sheesetfs  for the update.
